name: intake-axds
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - aiohttp
  - cf_pandas
  - h5netcdf
  - nested_lookup
  - pandas
  - pip
  - requests
  - shapely
  - pip:
    - git+https://github.com/intake/intake
    - intake-parquet
    - intake-xarray
    # - "dask[complete]"
