name: intake-axds
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - intake
  - intake-xarray
  - pandas
  - pip
  - requests
  - pip:
    - cf-pandas
