name: test_env_intake-axds
channels:
  - conda-forge
dependencies:
  - python=3.9
  ############## These will have to be adjusted to your specific project
  - intake
  - intake-xarray
  - pandas
  - requests
  ##############
  - pytest
  - pip:
    - cf-pandas
    - codecov
    - pytest-cov
    - coverage[toml]
