name: intake-axds_docs
channels:
  - conda-forge
  - nodefaults
dependencies:
   - python=3.9
   # If your docs code examples depend on other packages add them here
   - intake-xarray
   - pandas
   - requests
   # These are needed for the docs themselves
   - jupytext
   - numpydoc
   - sphinx
   - sphinx-markdown-tables
   - ipython
   - jinja2
   - nbconvert
   - nbformat
   - ipykernel
   - pandoc
   - pip
   - recommonmark
   - pip:
     - git+https://github.com/intake/intake
     - cf-pandas
     - docrep<=0.2.7
     - furo
     - nbsphinx>=0.8.7
     - jupyter_client
     - myst-nb
     - sphinx-copybutton
     - sphinxcontrib-srclinks
